### ISSUE TITLE
Aerfalle's Greater Ward

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE-World-16PY-Patches#139]
I was working with Aerfalle''s Mana-infused Pallium and found that Aerfalle's Greater Ward only increased the Armor Level by 20, in looking it up I found the correct increase is to be 400. Checking the spell (ID 5009) I found the increase in the sql file to be 20 just giving a heads up.

**Comment by Theran578** [comment]
Fixed in content PR #141
