### ISSUE TITLE
Composite weapons should be ivory-able but not have wieldable-by pre-set

### ISSUE THREAD

**Issue by euphemos** [ACEmulator/ACE-World-16PY-Patches#1396]
Composite weapons (handle/fine/superb/exquisite) should not be pre-ivoried with the wieldable-by set, just ivoryable.

If this bug is accepted, we should also make upgraded bows a valid target for infinite ivory.

I am happy to make the necessary updates if core team agrees this is a bug in the current recipe.

**Comment by ziang4891** [comment]
This is incorrect.  The weapons were tagged by the player when created
