### ISSUE TITLE
Lower quality base Composite Bows should not be eligible for upgrade

### ISSUE THREAD

**Issue by euphemos** [ACEmulator/ACE-World-16PY-Patches#1397]
Only a perfectly crafted bow (6963) should eligible for new handles, but the recent recipe update allows crap bows to get the better stats. 

Source: memory and item description indicating a perfectly crafted bow is required.

If the core team agrees, I will be happy to make this change and also double-check crossbows.

**Comment by jovrtn** [comment]
Fixed with #1388
