### ISSUE TITLE
Composite Bow with Handle has incorrect base MeleeD modifier

### ISSUE THREAD

**Issue by euphemos** [ACEmulator/ACE-World-16PY-Patches#1398]
The current 33997 weenie has 29% base MeleeD. It self-buffs to 44%. The base should be 12%, self-buffing to 27%.

The built-in Defender VI brings adds 15% to 12% to get 27%. That's what we see in the cached weenie. It is also what we see in the 2012 video https://www.youtube.com/watch?v=3RsmCPwMNsI&t=648s. 

The PCAP appears to have has BD7 aura active to get it to 29, which confused things at some point.

Bow/Exquisite Handle (33996) PCAP and Cache has WEAPON_DEFENSE_FLOAT (29) => 1.17
**It is illogical that Bow/Handle has higher base stats and buffed stats than Bow/Exquisite.**

If the core team agrees, I am happy to make these updates.

**Comment by jovrtn** [comment]
Fixed with #1388
