### ISSUE TITLE
Exploration Society Agents Don't hand out Facility Hub Portal Gems

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE-World-16PY-Patches#51]
When speaking to one of the explorer society agents (Flinrala_Ryndmad, Oi-Tong_Ye, Mara_al-Luq) You should receive a facility hub portal gem. If you give the gem back to the NPC, then you should learn the Facility Hub Recall spell. Right now there is no way to get to the facility hub other than the town network. 

https://asheron.fandom.com/wiki/Facility_Hub_Portal_Gem

https://asheron.fandom.com/wiki/Exploration_Society_Agent

https://asheron.fandom.com/wiki/Flinrala_Ryndmad

https://asheron.fandom.com/wiki/Oi-Tong_Ye

https://asheron.fandom.com/wiki/Mara_al-Luq

**Comment by kdmxp256** [comment]
Updated in https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/53
