### ISSUE TITLE
Missing Metos Portal

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE-World-16PY-Patches#525]
went to use the Halls of Metos  (Wai Jhou) at Imuth Maer Doquin found it was missing. Here is the corrected Landblock File (C770.sql) plus the link:
http://acpedia.org/wiki/Imuth_Maer_Doquin

[C770.zip](https://github.com/ACEmulator/ACE-World-16PY-Patches/files/4908216/C770.zip)

**Comment by ziang4891** [comment]
I haven't released the patch, yet, that includes the portal
