### ISSUE TITLE
Issues with Rampager

### ISSUE THREAD

**Issue by adamplumb** [ACEmulator/ACE-World-16PY-Patches#814]
Looks like this recent commit (https://github.com/ACEmulator/ACE-World-16PY-Patches/commit/794db5337ba1165763e4cea99c49013df8da578b) updated some things about Rampagers.

- Removes the Attackable bool property and some others
- Adds the ruined amulet as a create list item, but the weenie (43146) has no row in the weenies table.  

Probably some other issues but I noticed these.

**Comment by ziang4891** [comment]
The Attackable bool is a default property, so it doesn't need to be listed for attackable mobs

**Comment by ziang4891** [comment]
Missing Ruined Amulets added in PR#815
