### ISSUE TITLE
Fear Factory quest progress/released flag does not clear upon completion

### ISSUE THREAD

**Issue by trothenberg** [ACEmulator/ACE-World-16PY-Patches#876]
The Fear Factory released flag does not appear to be cleared properly when the quest is turned in.  Because of this, after a player completes the quest once, they can turn in to Geilla every 20 hours for rewards without having to run the quest again.  The Shadow Captives in the Fear Factory dungeon remain unresponsive to the player.

My amateur eyes were not able to identify the fault: the QuestCompletions attribute is reset to 0 when Geilla gives the quest.

**Comment by LtRipley36706** [comment]
Fixed in ACEmulator/ACE-World-16PY-Patches#875
